#!/usr/bin/env bash
set -euo pipefail

CHATTERBOX_TTS_RUNTIME="${CHATTERBOX_TTS_RUNTIME:-/home/shkas/projects/raaz/.runtime/chatterbox-tts}"
CHATTERBOX_TTS_VENV="${CHATTERBOX_TTS_VENV:-$CHATTERBOX_TTS_RUNTIME/.venv}"
CHATTERBOX_TTS_PYTHON="${CHATTERBOX_TTS_PYTHON:-$CHATTERBOX_TTS_VENV/bin/python}"

CHATTERBOX_TTS_HOST="${CHATTERBOX_TTS_HOST:-127.0.0.1}"
CHATTERBOX_TTS_PORT="${CHATTERBOX_TTS_PORT:-8126}"
CHATTERBOX_TTS_DEVICE="${CHATTERBOX_TTS_DEVICE:-cpu}"
CHATTERBOX_TTS_MODEL="${CHATTERBOX_TTS_MODEL:-turbo}"
CHATTERBOX_TTS_MAX_CHARS="${CHATTERBOX_TTS_MAX_CHARS:-1200}"
CHATTERBOX_TTS_STARTUP_TIMEOUT_SECONDS="${CHATTERBOX_TTS_STARTUP_TIMEOUT_SECONDS:-300}"
CHATTERBOX_TTS_MODEL_ROOT="${CHATTERBOX_TTS_MODEL_ROOT:-$CHATTERBOX_TTS_RUNTIME/models}"
CHATTERBOX_TTS_LOCAL_ONLY="${CHATTERBOX_TTS_LOCAL_ONLY:-}"

CHATTERBOX_TTS_STATE_DIR="${CHATTERBOX_TTS_STATE_DIR:-$HOME/.openclaw/chatterbox-tts}"
CHATTERBOX_TTS_PID_FILE="${CHATTERBOX_TTS_PID_FILE:-$CHATTERBOX_TTS_STATE_DIR/server.pid}"
CHATTERBOX_TTS_LOG_FILE="${CHATTERBOX_TTS_LOG_FILE:-$CHATTERBOX_TTS_STATE_DIR/server.log}"
CHATTERBOX_TTS_HEALTH_URL="${CHATTERBOX_TTS_HEALTH_URL:-http://${CHATTERBOX_TTS_HOST}:${CHATTERBOX_TTS_PORT}/health}"

# Output tuning for voice-note delivery (WhatsApp/Telegram)
CHATTERBOX_TTS_OUTPUT_BITRATE="${CHATTERBOX_TTS_OUTPUT_BITRATE:-48k}"
CHATTERBOX_TTS_OUTPUT_APPLICATION="${CHATTERBOX_TTS_OUTPUT_APPLICATION:-audio}"
CHATTERBOX_TTS_OUTPUT_FILTER="${CHATTERBOX_TTS_OUTPUT_FILTER:-loudnorm=I=-18:TP=-2:LRA=11}"

mkdir -p "$CHATTERBOX_TTS_STATE_DIR"
